### ISSUE TITLE
File Deletion

### ISSUE THREAD

**Issue by matm2** [haste/oUF#259]
Works great other than I found 1 bug with Curse Client. I Downloaded it from Wowinterface and everything is there in the right place. When I pres refresh on Curse Client it brings up oUF_Gvv update (I don't have oUF_Gvv installed) when I tried deleting it, it deletes the Pure oUF File in my addons folder. Let me know by email if you need any further detail:)

**Comment by haste** [comment]
This is an issue with the Curse Client and not oUF. Not much I can do to solve it.

They apparently have a new client around the corner, but that's been said since last year...
