### ISSUE TITLE
[Bug] ClassIcons: Druid Combo Points fail to show sometimes

### ISSUE THREAD

**Issue by Blazeflack** [haste/oUF#278]
Sometimes when shifting into cat form, the following line will fail to evaluate to true:
```
if(not RequirePower or RequirePower == UnitPowerType('player')) then
```
The UnitPowerType('player') call will return values reflecting the human form, so "0 MANA"

Technically this is a bug on Blizzards end, but perhaps it can be worked around by adding a small delay to the Visibility update.

**Comment by p3lim** [comment]
You should update your clone.

**Comment by Blazeflack** [comment]
Oh right, I forgot about that. I would actually like to keep the mechanism of only showing combo points as feral while in cat.

I guess I will have to see if I can find a way to fix it while keeping this mechanism in place.

**Comment by Blazeflack** [comment]
Closing this one, as it is an issue on our end only.

**Comment by ls-** [comment]
Well, this issue is on Blizz end. Even default UI is affected by it, and I'm not sure that they're going to fix it :(
