### ISSUE TITLE
[Bug] ClassIcons: Not updating max combo points for Rogues with Anticipation

### ISSUE THREAD

**Issue by Blazeflack** [haste/oUF#280]
When you switch between Anticipation and any of the other talents on the row, the max amount of combo points is not updated for Rogues.

I removed my own modifications to the file to make sure this was an issue with the code in its default state.

**Comment by Blazeflack** [comment]
I made some modifications to try and fix this on my own, and while doing so I noticed the following:

- PLAYER_TALENT_UPDATE triggers first, but at this point UnitPowerMax does not return the correct value for Combo Points.
- UNIT_POWER_FREQUENT triggers next, and now UnitPowerMax returns the correct value.
- When UNIT_POWER_FREQUENT triggers, the powerType is "ENERGY", so the Update will never happen because of the check at the top where it matches powerType to ClassPowerType.

**Comment by p3lim** [comment]
Works fine for me, are you sure you have updated oUF and have actually created up to 8 classicons in your layout?

**Comment by Blazeflack** [comment]
I will double check this and get back to you.

**Comment by Blazeflack** [comment]
I replaced the entire contents of my classicons.lua file with the code taken from this repository.

When I change to/from the Anticipation talent on my rogue, I see the Update function fire twice, but it never gets past the initial check at the top.
Code:
```	print("Update:", "event:", event, "unit:", unit, "powerType:", powerType)
	if(not (unit == 'player' and powerType == ClassPowerType)
		and not (unit == 'vehicle' and powerType == 'COMBO_POINTS')) then
		return
	end
	print("Update passed the 'return' check")
```
Result:
```
Update: event: UNIT_POWER_FREQUENT unit: player powerType: ENERGY
Update: event: UNIT_POWER_FREQUENT unit: player powerType: ENERGY
```

**Comment by p3lim** [comment]
Nothing will fire an update when you change talents (unless you went from Deeper Stratagem to Anticipation and you previously had 6 combo points, forcing an update due to change in max).

Only times a PTU will force an actual update is if the element gets disabled, and in such a case the event will be `'ClassPowerDisable'`.

**Comment by p3lim** [comment]
Might want to add the `'UNIT_MAXPOWER'` event to `ClassPowerEnable` to "fix" this.

**Comment by Blazeflack** [comment]
Ahh yeah, That makes sense. Thank you.
