### ISSUE TITLE
UnitIsTapped doesn't exists anymore

### ISSUE THREAD

**Issue by Itrulia** [haste/oUF#284]
Error that is thrown: `oUF\elements\power.lua:150: attempt to call global 'UnitIsTapped' (a nil value)`

UnitIsTapDenied replaced UnitIsTapped and should be now used AFAIK

PS: Same for `health.lua`

**Comment by Itrulia** [comment]
Nope I use the latest version (from wowinterface)

Searching for UnitIsTapped in the repo still shows hits

https://github.com/haste/oUF/search?utf8=%E2%9C%93&q=UnitIsTapped

**Comment by haste** [comment]
The WoWI release is currently not legion ready.

**Comment by Itrulia** [comment]
Ok, then ill close this one :), ty!
