### ISSUE TITLE
issue with ClassIcons visibility when switching spec for druid

### ISSUE THREAD

**Issue by gagou** [haste/oUF#291]
Currently displaying combo points with class icons module for druid require the shred spell, this spell is given when in feral spec or any other spec with the "feral affinity" talent. (without the feral affinity you can still gain combo points with Swipe but you can't use those combo points so it's a good choice to use shred I think)

When switching from guardian without feral affinity to guardian with feral affinity or to feral spec the Visibility function is executed when the SPELLS_CHANGED event is fired.
The visibility function is unregistering the SPELLS_CHANGED event.
Switching back to a spec without the shred spell will not execute the Visibility function as the SPELLS_CHANGED event is unregistered.
Maybe we should not unregister SPELLS_CHANGED ?

**Comment by p3lim** [comment]
> ... but you can't use those combo points so it's a good choice to use shred

Exactly.

> Maybe we should not unregister SPELLS_CHANGED ?

The problem is rather `PLAYER_TALENT_UPDATE` not being registered unless `RequireSpec` is set, I'll fix that.
