### ISSUE TITLE
RuneBar: Runes that are energized, should they be instantly refreshed as active?

### ISSUE THREAD

**Issue by Blazeflack** [haste/oUF#294]
When a rune is energized, as indicated with a 2nd "true" argument in the RUNE_POWER_UPDATE event, should the rune with this runeID be instantly refreshed and displayed as available?

An Unholy Death Knight with the "Pestilent Pustules" talent has the ability to instantly gain 1 rune for every 6 Festering Wounds they burst (using Festering Strike and Scourge Strike).

I checked what "GetRuneCooldown" returns for a runeID that was energized, and it says that the rune is _not_ ready even though it is. I'm thinking that we may have to simply overwrite the "runeReady" variable with the "isEnergize" argument.

Something like this:
```
- local Update = function(self, event, rid)
+ local Update = function(self, event, rid, isEnergize)

- if(runeReady) then
+ if(isEnergize or runeReady) then

- return runes:PostUpdate(rune, rid, start, duration, runeReady)
+ return runes:PostUpdate(rune, rid, start, duration, isEnergize or runeReady)
```

In its current state you may experience the rune bar showing 0 active runes even though you just gained a rune through the talent.

**Comment by p3lim** [comment]
A fix for this was merged into #269.
