### ISSUE TITLE
portrait: script ran too long

### ISSUE THREAD

**Issue by Blazeflack** [haste/oUF#295]
I have seen reports of a script ran too long error in the "Update" function of the oUF portrait element.

This is the error:
```
Message: ...ce\AddOns\ElvUI\Libraries\oUF\elements\portraits.lua:63: script ran too long
Time: 09/09/16 19:47:52
Count: 1
Stack: [C]: in function `SetUnit'
...ce\AddOns\ElvUI\Libraries\oUF\elements\portraits.lua:63: in function <...ce\AddOns\ElvUI\Libraries\oUF\elements\portraits.lua:43>
(tail call): ?
(tail call): ?

Locals: 
```

I have been unable to reproduce the issue myself. The user who alerted me to this error experiences it on his Horde Blood Elf Rogue and Horde Blood Elf Demon Hunter (in case that matters).

I'm not sure why this script would take too long to execute, as it is fairly short in nature.

I have verified that I use the exact same code as in the oUF repository, and my portrait.lua file matches the one here exactly.

Any ideas?

**Comment by Blazeflack** [comment]
Actually the issue may be on Blizzards end in the :SetUnit API.
See https://www.wowace.com/addons/shadowed-unit-frames/tickets/944-script-ran-too-long-on-kargath

In this case the error happened on the :SetUnit call as well, just like in the error I mentioned in the ticket.

**Comment by haste** [comment]
Yeah, the element is already optimized to only call :SetUnit when it has
to, so there isn't much more we can do from oUF's point of  view. :(

**Comment by Blazeflack** [comment]
Yeah that's what I thought. Thanks for verifying it :).

I have messaged someone I know who works at Blizzard and asked for his opinion on the matter. Perhaps there is something they can optimize on their end.

It doesn't seem to affect many people though, I have only seen 3 reports so far, so it may not be a high priority for Blizzard.
